export const environment = {
    baseUrl:'http://localhost:9090/api',
    urlAlumnoCurso: '/alumnoCurso/',
    urlAsignatura: '/asignatura/',
    urlAsignaturaProfeCurso: '/asignaturaProfeCurso/',
    urlAsistenciaEvento: '/asistenciaEvento/',
    urlAula: '/aula/',
    urlRolUsuario: '/rolUsuario/',
    urlContacto: '/contacto/',
    urlCurso: '/curso/',
    urlDepartamento: '/departamento/',
    urlDocumentoProgramatico: '/documentoProgramatico/',
    urlEquipoDirectivo: '/equipoDirectivo/',
    urlEvento: '/evento/',
    urlHorario: '/horario/',
    urlEventoGaleria: '/eventoGaleria/',
    urlCategorias:'/categoria/',
    urlNoticia: '/noticia',
    urlNoticiaGaleria: '/noticiaGaleria/',
    urlReserva: '/reserva/',
    urlRol: '/rol/',
    urlTemario: '/temario/',
    urlTipoAula: '/tipoAula/',
    urlTipoCurso: '/tipoCurso/',
    urlTipoEvento: '/tipoEvento/',
    urlTipoNoticia: '/tipoNoticia/',
    urlUsuario: '/usuario/',
    urlAuth:'/auth',
    urlLogin:'/login',
    urlRegistro:'/register',
    urlUsers:'/usuario/',
    urlRolAsignado:'/rolUsuario/',
    urlNoticiasSocket:'http://localhost:8090',
    urlEventosSocket: 'http://localhost:8090',
};
