export const environment = {
    baseUrl:'http://localhost:9090/api',
    urlCategorias:'/categorias',
    urlNoticias:'/noticias',
    urlSecciones:'/secciones',
    urlEventos: '/eventos',
    urlEnlace:'/enlaces',
    urlAuth:'/auth',
    urlLogin:'/login',
    urlRegistro:'/register',
    urlUsers:'/usuario',
    urlRol:'/roles',
    urlRolAsignado:'/rolesAsignados',
    urlNoticiasSocket:'http://localhost:8090',
    urlAulas:'/aulas',
    urlFranjas:'/franjas',
    urlHorarios:'/horarios',
    urlAsistencias:'/asistencia',
    urlReservas:'/reservas',
    urlEventosSocket: 'http://localhost:8090',
    urlFotosEventos:'/uploads/eventos',
    urlFotosGaleria: '/uploads/galerias',
    urlFotosNoticias: '/uploads/noticias',
    urlFotosSecciones:'/uploads/secciones',
    urlGaleria: '/galeria',
    urlContacto: '/contacto',
    urlTipoCurso: '/tipoCurso',
    urlAsignatura: '/asignatura',
    urlTemario: '/temario',
    urlDocumentoProgramatico: '/documentoProgramatico',
    urlDepartamento: '/departamento',
    urlEquipoDirectivo: '/equipoDirectivo',
    urlCurso: '/curso'
};
